config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index' #to always go to the index page if a page is not specified
  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create, ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :lists, through: :bookmarks
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<br>
<h1>Which movie would you like to add?</h1>
<br>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, as: :select %>
  <%= f.input :comment %>
  <%= f.input :comment %>

  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP3LTEunoXwfZOaFQsKA3MRMr4MNim0eC2XQ&usqp=CAU">
  <div class="container">
    <h1>Movie Lists</h1>
    <p>Create lists of movies any way you like!</p>
  </div>
</div>
<div>
<div class="card-category">
  <h2>Your Lists</h2>
</div>
<div class="cards">
  <%@lists.each do |list| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://picsum.photos/200/300)">
      <%= link_to list.name, list_path(list) %>
      <%= link_to "+", list_path(list), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<br>
<h1>What do you want to name your list?</h1>
<p><%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>

  <%= f.submit %>
  <% end %>
</p>

app/views/lists/show.html.erb
<br>
<h1><%= @list.name %></h1>
<br>
<ul>
  <% @list.movies.each do |movie| %>
  <li><%= movie.title %></li>
  <% end %>
</ul>
<br>
<br>
<%= link_to "Add Movie", new_list_bookmark_path(@list), class: "btn btn-secondary" %>
<br>
<%# <br> %>
<%# <%= link_to "Delete Movie", bookmark_path(@bookmark), class: "btn btn-warning" %>
<br>
<br>
<%= link_to "Back to All Lists", lists_path, class: "btn btn-primary" %>